# port to listen on
port: 8000
# requires all requests to have a key attached
auth: false
# used if auth is enabled
keys: []
# debug mode - prints request information in console.
debug: false

separator: ","