name: PlaceholderWeb
api-version: 1.17
version: 1.2
main: me.blake.papiweb.PlaceholderWeb
depend: ["PlaceholderAPI"]
commands:
  placeholderweb:
    description: Manage PlaceholderWeb
    usage: /<command> <generate/reload/debug/generateurl>
    aliases: ["pweb"]
    permission: placeholderweb.admin
